"""empty message

Revision ID: 1c2b9db9b016
Revises: 866043b3c23e
Create Date: 2022-06-16 22:10:59.000861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2b9db9b016'
down_revision = '866043b3c23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('centername', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('reservetime', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'user', ['reservetime'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'reservetime')
    op.drop_column('user', 'centername')
    # ### end Alembic commands ###
